# -*- coding: utf-8 -*-
"""scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ozb1SaVKYEDkefHT36cKixmmELxh8nsZ

## Scraping Module
"""

import os

class Scraping:
    def __init__(self, IN_COLAB):
        if IN_COLAB is True: 
          self.base_path = "/content/"
        else: 
          self.base_path = "/workspaces/"

        # Create the directory if it doesn't exist
        kaggle_dir = os.path.expanduser('~/.kaggle')
        os.makedirs(kaggle_dir, exist_ok=True)

        # Copy kaggle.json to the directory
        kaggle_json_src = self.base_path + 'final_project/config/kaggle.json'
        kaggle_json_dst = os.path.join(kaggle_dir, 'kaggle.json')
        os.system(f'cp {kaggle_json_src} {kaggle_json_dst}')

        # Set permissions for kaggle.json
        os.system(f'chmod 600 {kaggle_json_dst}')

        # Import the kaggle module
        import kaggle

    def kaggle_scrape(self):
        # Download the dataset using the kaggle CLI
        os.system('kaggle datasets download -d mohamedbakhet/amazon-books-reviews')

        # Unzip the downloaded file
        os.system(f'unzip -q {self.base_path}/amazon-books-reviews.zip -d {self.base_path}final_project/data')