# -*- coding: utf-8 -*-
"""scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ozb1SaVKYEDkefHT36cKixmmELxh8nsZ

## Scraping Module
"""

class Scraping:
    def __init__(self):
        !mkdir -p ~/.kaggle
        !cp ../config/kaggle.json ~/.kaggle/
        !chmod 600 ~/.kaggle/kaggle.json
        import kaggle

    def kaggle_scrape(self):
        !kaggle datasets download -d mohamedbakhet/amazon-books-reviews
        !mv /workspaces/final_project/src/amazon-books-reviews.zip /workspaces/final_project/data/
        !unzip -q /workspaces/final_project/data/amazon-books-reviews.zip -d /workspaces/final_project/data

scraping = Scraping()
scraping.kaggle_scrape()